// Code generated by MockGen. DO NOT EDIT.
// Source: golang/service (interfaces: LoadService)

// Package Service is a generated GoMock package.
package Service

import (
	dto "golang/dto"
	errs "golang/errs"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLoadService is a mock of LoadService interface.
type MockLoadService struct {
	ctrl     *gomock.Controller
	recorder *MockLoadServiceMockRecorder
}

// MockLoadServiceMockRecorder is the mock recorder for MockLoadService.
type MockLoadServiceMockRecorder struct {
	mock *MockLoadService
}

// NewMockLoadService creates a new mock instance.
func NewMockLoadService(ctrl *gomock.Controller) *MockLoadService {
	mock := &MockLoadService{ctrl: ctrl}
	mock.recorder = &MockLoadServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoadService) EXPECT() *MockLoadServiceMockRecorder {
	return m.recorder
}

// GetLoadDocumentsService mocks base method.
func (m *MockLoadService) GetLoadDocumentsService(arg0 dto.LoadDocumentsReqDTO) (*dto.LoadDocumentsResDTO, *errs.AppErrorvalidation) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadDocumentsService", arg0)
	ret0, _ := ret[0].(*dto.LoadDocumentsResDTO)
	ret1, _ := ret[1].(*errs.AppErrorvalidation)
	return ret0, ret1
}

// GetLoadDocumentsService indicates an expected call of GetLoadDocumentsService.
func (mr *MockLoadServiceMockRecorder) GetLoadDocumentsService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadDocumentsService", reflect.TypeOf((*MockLoadService)(nil).GetLoadDocumentsService), arg0)
}

// GetLoadSearchResultService mocks base method.
func (m *MockLoadService) GetLoadSearchResultService(arg0 *dto.LoadSearchReqDTO) (*dto.LoadSearchResultResDTO, *errs.AppErrorvalidation) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadSearchResultService", arg0)
	ret0, _ := ret[0].(*dto.LoadSearchResultResDTO)
	ret1, _ := ret[1].(*errs.AppErrorvalidation)
	return ret0, ret1
}

// GetLoadSearchResultService indicates an expected call of GetLoadSearchResultService.
func (mr *MockLoadServiceMockRecorder) GetLoadSearchResultService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadSearchResultService", reflect.TypeOf((*MockLoadService)(nil).GetLoadSearchResultService), arg0)
}
