// Code generated by MockGen. DO NOT EDIT.
// Source: golang/service (interfaces: BookService)

// Package Service is a generated GoMock package.
package Service

import (
	dto "golang/dto"
	errs "golang/errs"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBookService is a mock of BookService interface.
type MockBookService struct {
	ctrl     *gomock.Controller
	recorder *MockBookServiceMockRecorder
}

// MockBookServiceMockRecorder is the mock recorder for MockBookService.
type MockBookServiceMockRecorder struct {
	mock *MockBookService
}

// NewMockBookService creates a new mock instance.
func NewMockBookService(ctrl *gomock.Controller) *MockBookService {
	mock := &MockBookService{ctrl: ctrl}
	mock.recorder = &MockBookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookService) EXPECT() *MockBookServiceMockRecorder {
	return m.recorder
}

// BookLTLService mocks base method.
func (m *MockBookService) BookLTLService(arg0 *dto.BookLTLRequestDTO) (*dto.BookLTLResponseDto, *errs.AppErrorvalidation) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookLTLService", arg0)
	ret0, _ := ret[0].(*dto.BookLTLResponseDto)
	ret1, _ := ret[1].(*errs.AppErrorvalidation)
	return ret0, ret1
}

// BookLTLService indicates an expected call of BookLTLService.
func (mr *MockBookServiceMockRecorder) BookLTLService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookLTLService", reflect.TypeOf((*MockBookService)(nil).BookLTLService), arg0)
}
